export const FETCH_FILTERED_EPISODE_LIST_REQUEST =
  "FETCH_FILTERED_EPISODE_LIST_REQUEST";
export const FETCH_FILTERED_EPISODE_LIST_SUCCESS =
  "FETCH_FILTERED_EPISODE_LIST_SUCCESS";
export const FETCH_EPISODE_ERROR = "FETCH_EPISODE_ERROR";
export const RESET_EPISODE_STATE = "RESET_EPISODE_STATE";
