export const FETCH_FILTERED_CHARACTER_LIST_REQUEST =
  "FETCH_FILTERED_CHARACTER_LIST_REQUEST";
export const FETCH_CHARACTER_LIST_REQUEST = "FETCH_CHARACTER_LIST_REQUEST";
export const FETCH_CHARACTER_LIST_SUCCESS = "FETCH_CHARACTER_LIST_SUCCESS";
export const FETCH_CHARACTER_DETAILS_REQUEST =
  "FETCH_CHARACTER_DETAILS_REQUEST";
export const FETCH_CHARACTER_DETAILS_SUCCESS =
  "FETCH_CHARACTERS_DETAILS_SUCCESS";
export const FETCH_CHARACTER_ERROR = "FETCH_CHARACTER_ERROR";
export const RESET_CHARACTER_STATE = "RESET_CHARACTER_STATE";
export const IS_LOADING_CHARACTERS = "IS_LOADING_CHARACTERS";
